name: shared_preferences_mega
description: A library that provides a lot of aditional tools to Shared Preferences
repository: https://github.com/LuisCarrizo/shared_preferences_mega
documentation: https://github.com/LuisCarrizo/shared_preferences_mega/wiki/Documentation
issue_tracker: https://github.com/LuisCarrizo/shared_preferences_mega/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22

version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true
